baseurl: /tripod.js
documentationLinks:
    Quick Start: 
    The Tripod Instance: the-instance.html
    Getting and Storing Data in the Instance: getting-and-storing-data-in-the-instance.html
    Data binding and the DOM: data-binding-and-the-dom.html
    Namespaces: namespaces.html
    Using Binding Modifiers: using-binding-modifiers.html
    getAll, loadAll, pushAll, syncAll: get-load-push-sync-all.html
    saveState and revert: savestate-and-revert.html
    Node Properties Used for Data Binding: node-properties-used-for-data-binding.html
    Utility Functions: utility-functions.html
    More Examples: more-examples.html